package com.ecommerce.homeproducts.dto;

public enum Category {
    FURNITURE,
    KITCHEN_APPLIANCES,
    HOME_DECOR,
    CLEANING_SUPPLIES,
    BATHROOM_ESSENTIALS,
    LIGHTING,
    STORAGE_ORGANIZATION,
    GARDENING,
    ELECTRONICS,
    BEDDING,
    TABLEWARE,
    SECURITY_DEVICES
}
